[workspace]
authors = ["TheSkyentist <raphael.hviding@gmail.com>"]
channels = ["conda-forge"]
name = "05_extras"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
download = """python -c 'import time; print("Downloading..."); time.sleep(1)'"""
preprocess = { cmd = "python data_prep.py", depends-on = ["download"] }
analyze = { cmd = "python analysis.py", depends-on = ["preprocess"] }

[dependencies]
python = ">=3.14.2,<3.15"
